include chadracula-evondev.conf

font_family MesloLGS NF
font_size   12

allow_remote_control yes
disable_ligatures no
enable_audio_bell no

shell zsh --login

clipboard_control write-clipboard write-primary read-clipboard read-primary

cursor_shape block
cursor_trail 3
cursor_trail_decay 0.1 0.4

url_style curly

remember_window_size  yes
remember_window_position yes
initial_window_width  80c
initial_window_height 40c
window_padding_width  20
cursor_blink_interval 0

tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style round

background_opacity            0.8
background_blur               64
scrollbar_handle_opacity      0
scrollbar_track_opacity       0
scrollbar_track_hover_opacity 0
confirm_os_window_close       0

sync_to_monitor no

hide_window_decorations titlebar-only
macos_colorspace displayp3

# Ensures the left alt key acts as a proper Meta key in Neovim
terminal_select_modifiers alt

# Alt+key sequences are sent as escape sequences.
macos_option_as_alt left

# Load platform specific config
include ${KITTY_OS}.conf
