#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

exec-once = systemctl --user start hyprpolkitagent
exec-once = hypridle

exec-once = waybar
exec-once = swaync

exec-once = awww-daemon
exec-once = sh -lc 'sleep 1; /home/javi/.local/bin/awww-random /home/javi/Pictures/Wallpapers/EpicUltraWide 300 >> /tmp/awww-random.log 2>&1'

exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data
